source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "faraday-retry"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jekyll-include-cache"

gem "rouge", "~> 4.4.0"
gem "webrick", "~> 1.8.2"
gem "json", "~> 2.7.5"
gem "net-http", "~> 0.4.1"
gem "uri", "~> 0.13.1"