apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations: 
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.app.url.api_root }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-apiserver-service
              port:
                name: api-web-port
