services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  static-site:
    build:
      context: ./demo_static_site/.
      dockerfile: Dockerfile
      # FBSE_DATABASEURL: ${FBSE_DATABASEURL}
    volumes:
      - ./demo_static_site:/usr/share/nginx/html
    ports:
      - "8081:80"
    depends_on:
      - api
  
  api:
    command: fastapi dev main.py --host 0.0.0.0 --port 3000 --reload
    build:
      context: ./api/.
      dockerfile: Dockerfile
      network: host
    environment:
      FBSE_APIKEY: ${FBSE_APIKEY}
      FBSE_AUTHDOMAIN: ${FBSE_AUTHDOMAIN}
      FBSE_PROJECTID: ${FBSE_PROJECTID}
      FBSE_STORAGEBUCKET: ${FBSE_STORAGEBUCKET}
      FBSE_MESSAGINGSENDERID: ${FBSE_MESSAGINGSENDERID}
      FBSE_APPID: ${FBSE_APPID}
    volumes:
      - ./api/src:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

